config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :home, only: [:index, :show]
  resources :users do
    resources :foods, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :recipes do
      member do
        patch 'toggle'
      end
      resources :recipe_foods, only: [:new, :create, :edit, :update, :destroy]
    end
    resources :public_recipes, only: [:index]
  end
  root 'home#index'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    can :read, Recipe, public: true

    return unless user.present? # additional permissions for logged in users (they can read their own posts)

    can(:read, Recipe, user:)

    return unless user.admin? # additional permissions for administrators

    can :manage, Recipe
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods, foreign_key: 'food_id'
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods, foreign_key: 'recipe_id'
  has_many :foods, through: :recipe_foods

  def total_price
    # Calculate the total price for the recipe
    recipe_foods.sum { |rf| rf.quantity * rf.food.price }
  end
end

app/models/recipe_food.rb
class RecipeFood < ApplicationRecord
  belongs_to :recipe
  belongs_to :food
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :recipes, foreign_key: 'user_id'
  has_many :foods, foreign_key: 'user_id'

  def shopping_list
    # Get all the recipe foods for the current user's recipes
    recipe_foods = RecipeFood.joins(:recipe).where(recipes: { user_id: id })

    # Group the recipe foods by their associated food items and calculate the total quantity required for each food item
    required_foods = recipe_foods.group(:food_id).sum(:quantity)

    # Create a hash to store the shopping list
    shopping_list = {}

    # Initialize total items and total value variables
    total_items = 0
    total_value = 0

    # Compare the total quantity of each food item required with the available quantity in the user's foods
    required_foods.each do |food_id, total_quantity_required|
      food = Food.find(food_id)
      available_quantity = food.quantity || 0
      quantity_to_buy = [0, total_quantity_required - available_quantity].max

      next unless quantity_to_buy.positive?

      # Calculate the total price for the required quantity
      total_price = food.price * quantity_to_buy
      shopping_list[food] = { quantity: quantity_to_buy, total_price: }

      # Increment total items and total value
      total_items += quantity_to_buy
      total_value += total_price
    end

    { shopping_list:, total_items:, total_value: }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[name email password password_confirmation])
    devise_parameter_sanitizer.permit(:account_update,
                                      keys: %i[name email password password_confirmation current_password])
  end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  def index
    @user = User.includes(foods: :recipe_foods).find(params[:user_id])
    @recipe_foods = RecipeFood.joins(recipe: :user).where(recipes: { user_id: current_user.id })
    p @recipe_foods
  end

  def new
    @food = Food.new
  end

  def create
    @food = Food.new(post_params)
    @food.user_id = current_user.id
    if @food.save
      redirect_to user_foods_path
    else
      render :new
    end
  end

  def destroy
    @food = Food.find(params[:id])
    @food.destroy
    redirect_to user_foods_path
  end

  def post_params
    params.require(:food).permit(:name, :measurement_unit, :price, :quantity)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index; end

  def show
    @shopping_list = current_user.shopping_list
  end
end

app/controllers/public_recipes_controller.rb
class PublicRecipesController < ApplicationController
  def index
    @public_recipes = Recipe.where(public: true)
      .includes(:user, :recipe_foods)
      .order(created_at: :desc)
      .left_joins(:recipe_foods)
      .group('recipes.id')
      .select('recipes.*, COUNT(recipe_foods.id) AS recipe_foods_count')
  end
end

app/controllers/recipe_foods_controller.rb
class RecipeFoodsController < ApplicationController
  def new
    @foods = current_user.foods.pluck(:name, :id)
    @recipe_food = RecipeFood.new
    @recipe = Recipe.find(params[:recipe_id])
  end

  def create
    @recipe_food = RecipeFood.new(post_params)
    if @recipe_food.save
      redirect_to user_recipe_path(user_id: current_user.id, id: @recipe_food.recipe_id)
    else
      render :new
    end
  end

  def destroy
    @recipe_food = RecipeFood.includes(:food).find(params[:id])
    @recipe_food.destroy
    redirect_to user_recipe_path(user_id: current_user.id, id: @recipe_food.recipe_id)
  end

  def edit
    @recipe_food = RecipeFood.find(params[:id])
    @recipe = Recipe.find(params[:recipe_id])
  end

  def update
    @recipe_food = RecipeFood.find(params[:id])
    @recipe_id = params[:recipe_id]
    if @recipe_food.update(post_params)
      redirect_to user_recipe_path(user_id: current_user.id, id: @recipe_food.recipe_id),
                  notice: 'The ingredient was successfully updated.'
    else
      redirect_to user_recipe_path(user_id: current_user.id, id: @recipe_food.recipe_id),
                  alert: 'The ingredient could not be updated.'
    end
  end

  def post_params
    params.require(:recipe_food).permit(:quantity, :food_id, :recipe_id)
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def index
    @user = User.includes(:foods, :recipes).find(params[:user_id])
  end

  def show
    @user = current_user
    @food = Food.all
    @recipe = Recipe.find(params[:id])
    @recipe_foods = RecipeFood.includes(food: :user).where(recipe_id: @recipe.id)
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = Recipe.new(post_params)
    @recipe.user_id = current_user.id
    if @recipe.save
      redirect_to user_recipes_path
    else
      render :new
    end
  end

  def destroy
    @recipe = Recipe.find(params[:id])
    @recipe.recipe_foods.destroy_all
    @recipe.destroy
    redirect_to user_recipes_path
  end

  def toggle
    @recipe = Recipe.find(params[:id])
    @recipe.update(public: !@recipe.public)
    redirect_back(fallback_location: root_path)
  end

  def post_params
    params.require(:recipe).permit(:name, :preparation_time, :cooking_time, :description, :public)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/public_recipes_helper.rb
module PublicRecipesHelper
end

app/helpers/recipe_foods_helper.rb
module RecipeFoodsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/foods/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Foods</title>
  <%= stylesheet_link_tag 'foods', media: 'all', 'data-turbolinks-track': 'reload' %>
</head>
<body>
  <div class="container">
    <%= button_to "Add food", new_user_food_path(user_id: @user.id), method: :get, class: "btn" %>

    <% if @user.foods.empty? %>
      <p>No food added yet</p>
    <% else %>
      <table class="foodTable">
        <thead>
          <tr>
            <th>Food</th>
            <th>Quantity</th>
            <th>Measurement Unit</th>
            <th>Unit Price</th>
            <th>Action</th>
          </tr>
        </thead>
        <tbody>
          <% @user.foods.each do |food| %>
            <tr>
              <td><%= food.name %></td>
              <td><%= food.quantity %></td>
              <td><%= food.measurement_unit %></td>
              <td>$<%= food.price %></td>
              <td>
                <% if current_user == food.user && !@recipe_foods.find { |rf| rf.food_id == food.id } %>
                  <%= button_to "Delete food", user_food_path(user_id: food.user_id, id: food.id), method: :delete, class: "action-btn" %>
                <% else %>
                  <span class="foodUsed">Food is being used in a recipe</span>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    <% end %>
    <br />
    <%= link_to "Back", root_path, class: "btn" %>
  </div>
</body>
</html>

app/views/foods/new.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Create Food Item</title>
  <%= stylesheet_link_tag 'foods_new', media: 'all', 'data-turbolinks-track': 'reload' %>
</head>
<body>
  <div class="container">
    <%= form_with model: @food, url: user_foods_path do |form| %>
      <h2>Create Food Item</h2>

      <div class="field">
        <%= form.label :name %>
        <%= form.text_field :name %>
      </div>

      <div class="field">
        <%= form.label :measurement_unit %>
        <%= form.select :measurement_unit, options_for_select(['Miligrams', 'Grams', 'Kilograms']), {}, { placeholder: "Select a Measurement Unit" } %>
      </div>

      <div class="field">
        <%= form.label :price %>
        <%= form.text_field :price, type: :number, step: "any" %>
      </div>

      <div class="field">
        <%= form.label :quantity %>
        <%= form.text_field :quantity, type: :number, step: "any" %>
      </div>

      <%= form.submit 'Create Item', class: "btn" %>
    <% end %>
  <br />
  <%= link_to "Back", user_foods_path(current_user), class: "btn" %>

  </div>
</body>
</html>

app/views/home/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Home</title>
  <%= stylesheet_link_tag 'home_index', media: 'all', 'data-turbolinks-track': 'reload' %>
</head>
<body>
  <div class="container">
    <div class= "welcome">
      <h1>Welcome to Recipe App</h1>
      <p>Explore and share your favorite recipes with others.</p>
      <p>
        <%= link_to "Browse Foods", user_foods_path(current_user), class: "btn" %>
        <%= link_to "Browse Recipes", user_recipes_path(current_user), class: "btn" %>
        <%= link_to "Browse Public Recipes", user_public_recipes_path(current_user), class: "btn" %>
      </p>
    </div>
  </div>
</body>
</html>

app/views/home/show.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Shopping List</title>
  <%= stylesheet_link_tag 'shopping_list', media: 'all', 'data-turbolinks-track': 'reload' %>
</head>
<body>
  <div class="container">
    <h2>Shopping List</h2>
    <% if @shopping_list[:shopping_list].any? %>
      <div class="items-information">
        <p>Amount of Food Items to Buy: <%= @shopping_list[:total_items] %></p>
        <p>Total Value of Food Needed: $<%= @shopping_list[:total_value] %></p>
      </div>
      <table>
        <thead>
          <tr>
            <th>Food</th>
            <th>Quantity</th>
            <th>Price</th>
          </tr>
        </thead>
        <tbody>
          <% @shopping_list[:shopping_list].each do |food, details| %>
            <tr>
              <td><%= food.name %></td>
              <td><%= details[:quantity] %></td>
              <td>$<%= details[:total_price] %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    <% else %>
      <p>No ingredients to buy. Your pantry is fully stocked!</p>
    <% end %>
  </div>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Recipe On Rails</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <link rel="icon" type="image/png" href="<%= asset_path('Recipe.png') %>">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>
  <%= stylesheet_link_tag 'navbar', media: 'all', 'data-turbolinks-track': 'reload' %>
</head>

<body>

  
  <!-- Header -->
  <header>
    <div class="logo">
      <img src="<%= asset_path('logo.png') %>" alt="Logo" width="40px">
      <h1>Recipe On Rails</h1>
    </div>  
    <nav>
      <ul>
        <% if user_signed_in? %>
          <li>Welcome, <%= current_user.name %></li>
          <li><%= link_to "Foods", user_foods_path(current_user) %></li>
          <li><%= link_to "Recipes", user_recipes_path(current_user) %></li>
          <li><%= link_to "Public Recipes", user_public_recipes_path(current_user) %></li>
          <li><%= link_to "Shopping List", home_path(current_user) %></li>
          <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
          <li><%= button_to "Sign out", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Sign Up", new_user_registration_path %></li>
        <% end %>
      </ul>
    </nav>
  </header>

  <!-- Flash Notice -->
  <% if notice.present? %>
    <p class="notice"><%= notice %></p>
  <% end %>

  <!-- Flash Alert -->
  <% if alert.present? %>
    <p class="alert"><%= alert %></p>
  <% end %>

  <%= yield %>
</body>
</html>

app/views/public_recipes/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Public Recipes</title>
  <%= stylesheet_link_tag 'public_recipe_index', media: 'all', 'data-turbolinks-track': 'reload' %>
</head>
<body>
  <div class="container">
    <h2>Public recipes</h2>


  <div class= "public-recipe">
    <% if @public_recipes.empty? %>
      <p>No public recipes added yet</p>
    <% else %>
      <% @public_recipes.each do |recipe| %>
        <div class="recipe-card">
          <div class="name-user">
            <h3><%= link_to recipe.name, user_recipe_path(user_id: recipe.user_id, id: recipe.id), class: "recipe-name" %></h3>
            <p>By: <%= recipe.user.name %></p>
          </div>
          <div class="data">
            <p class="total-items">Total food items: <%= recipe.recipe_foods_count %> </p>
            <p class="total-items">Total price: $<%= recipe.total_price %></p>
            <% if current_user == recipe.user  %>
              <div class= "actions">
                <%= button_to "Delete recipe", user_recipe_path(user_id: recipe.user_id, id: recipe.id), method: :delete, class: "btn" %>
              </div>
            <% end %>
          </div>
          <hr />
        </div>
      <% end %>
    <% end %>
  </div>
  <br />
  <%= link_to "Back", root_path, class: "btn" %>
  </div>
</body>
</html>

app/views/recipe_foods/edit.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Edit Recipe Ingredient</title>
  <%= stylesheet_link_tag 'recipe_food_edit', media: 'all', 'data-turbolinks-track': 'reload' %>
</head>
<body>
  <div class="container">
    <%= form_with(model: @recipe_food, url: user_recipe_recipe_food_path(current_user, @recipe.id, @recipe_food), local: true, method: :patch) do |form| %>
      <h1 class="comments-form-title">Edit <%= @recipe_food.food.name %></h1>
      <div class="field">
        <div>
          <%= form.label :quantity %>
          <%= form.text_field :quantity, type: :number, step: "any" %>
        </div>
        <%= form.hidden_field :food_id, value: @recipe_food.food_id %>
      </div>
      <%= form.submit 'Update Ingredient', class: "submit-btn" %>
    <% end %>
  </div>
</body>
</html>

app/views/recipe_foods/new.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Add Ingredient to Recipe</title>
  <%= stylesheet_link_tag 'recipe_food_new', media: 'all', 'data-turbolinks-track': 'reload' %>
</head>
<body>
  <div class="container">
    <%= form_with model: @recipe_food, url: user_recipe_recipe_foods_path(user_id: @recipe.user_id, recipe_id: @recipe.id) do |form| %>
      <h2>Add Ingredient to Recipe</h2>

      <%= form.hidden_field :recipe_id, value: @recipe.id %>

      <div class="field">
        <%= form.label :food_id %>
        <%= form.select :food_id, options_for_select(@foods), {}, { placeholder: "Select a Food" } %>
      </div>

      <div class="field">
        <%= form.label :quantity %>
        <%= form.text_field :quantity %>
      </div>

      <%= form.submit 'Add Ingredient', class: "btn" %>
    <% end %>
  </div>
</body>
</html>

app/views/recipes/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Recipes</title>
  <%= stylesheet_link_tag 'recipe_index', media: 'all', 'data-turbolinks-track': 'reload' %>
</head>
<body>
  <div class="container">
    <%= button_to "Add recipe", new_user_recipe_path(user_id: @user.id), method: :get, class: "btn" %>
    <br />
    <% if @user.recipes.empty? %>
      <p>No recipes added yet</p>
    <% else %>
      <% @user.recipes.each do |recipe| %>
        <div class="recipe">
        <div class="name-btn">
          <p class="recipe-title"><%= link_to recipe.name, user_recipe_path(user_id: recipe.user_id, id: recipe.id), class: "recipe-name" %></p>
          <% if current_user == recipe.user  %>
            <div class= "actions">
              <%= button_to "Delete recipe", user_recipe_path(user_id: recipe.user_id, id: recipe.id), method: :delete, class: "btn" %>
            </div>
          <% end %>
        </div>
        <p class="recipe-description"><%= recipe.description %></p>
        </div>
      <% end %>
    <% end %>
    <br />
    <%= link_to "Back", root_path, class: "btn" %>
  </div>
</body>
</html>

app/views/recipes/new.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Create Recipe</title>
  <%= stylesheet_link_tag 'recipe_new', media: 'all', 'data-turbolinks-track': 'reload' %>
</head>
<body>
  <div class="container">
    <%= form_with model: @recipe, url: user_recipes_path do |form| %>
      <h2>Create Recipe</h2>

      <div class="field">
        <%= form.label :name %>
        <%= form.text_field :name %>
      </div>

      <div class="field">
        <%= form.label :preparation_time  %>
        <%= form.text_field :preparation_time, type: :number, step: "any" %>
      </div>

      <div class="field">
        <%= form.label :cooking_time %>
        <%= form.text_field :cooking_time, type: :number, step: "any" %>
      </div>

      <div class="field">
        <%= form.label :description %>
        <%= form.text_field :description %>
      </div>

      <div class="field">
        <%= form.label :public %>
        <%= form.hidden_field :public, value: false %>
        <%= form.check_box :public %>
      </div>

      <%= form.submit 'Create Recipe', class: "btn" %>
    <% end %>

    <br />

    <%= link_to "Back", user_recipes_path(current_user), class: "btn" %>
  </div>
</body>
</html>

app/views/recipes/show.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Recipe Details</title>
  <%= stylesheet_link_tag 'recipe_show', media: 'all', 'data-turbolinks-track': 'reload' %>
</head>
<body>
  <div class="container">
    <h1><%= @recipe.name %></h1>
    
    <div class= "recipe_information">
      <div>
        <h4>Preparation Time: <%= @recipe.preparation_time.to_i %> minutes</h4>
        <h4>Cooking Time: <%= @recipe.cooking_time.to_i %> minutes</h4>
        <p><%= @recipe.description %></p>
      </div>

      <div class="toggle-button">
        <% if current_user == @recipe.user %>
          <%= button_to "Toggle Public", toggle_user_recipe_path(user_id: current_user.id, id: @recipe.id), method: :patch, class: "btn toggle-public-btn" %>
          <h4>Public: <%= @recipe.public.to_s %></h4>
        <% end %>
      </div>
    </div>
<br />
    <div class= "buttons">
      <% if current_user == @recipe.user %>
        <%= button_to "Add ingredient", new_user_recipe_recipe_food_path(recipe_id: @recipe.id), method: :get, class: "btn" %>
        <%= button_to "Generate Shopping List", home_path, method: :get, class: "btn" %>
      <% end %>
    </div>

    <hr />

    <% if @user.foods.empty? %>
      <p>No food ingredients yet</p>
    <% else %>
      <table class="foodTable">
        <thead>
          <tr>
            <th>Food</th>
            <th>Quantity</th>
            <th>Value</th>
            <th>Actions</th>
          </tr>
        </thead>
        <tbody>
          <% @recipe_foods.each do |recipe| %>
            <tr>
              <td><%= recipe.food.name %></td>
              <td><%= recipe.quantity %></td>
              <td>$<%= recipe.food.price * recipe.quantity %></td>
              <td>
                <div class= "actions">
                  <% if current_user == @recipe.user %>
                    <%= button_to "Modify", edit_user_recipe_recipe_food_path(user_id: @recipe.user_id, recipe_id: @recipe.id, id: recipe.id), method: :get, class: "action-btn"  %>
                    <%= button_to "Remove", user_recipe_recipe_food_path(user_id: @recipe.user_id, recipe_id: @recipe.id, id: recipe.id), method: :delete, class: "action-btn"  %>
                  <% end %>
                </div>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    <% end %>
    <br />
    <%= link_to "Back", user_recipes_path(current_user), class: "btn" %>
  </div>
</body>
</html>